In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install opendatasets
!pip install pandas

In [3]:
import opendatasets as od
import pandas

od.download("https://www.kaggle.com/competitions/titanic")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: nureanikaanan
Your Kaggle Key: ··········


100%|██████████| 34.1k/34.1k [00:00<00:00, 33.2MB/s]


Extracting archive ./titanic/titanic.zip to ./titanic


In [4]:
# !pip install numpy==1.24.4
# !pip install pandas --upgrade
# !pip install matplotlib --upgrade

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os

In [5]:
!pip install seaborn --upgrade
!pip install sklearn --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 4.5 MB/s eta 0:00:00
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.12.2
    Uninstalling seaborn-0.12.2:
      Successfully uninstalled seaborn-0.12.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metada

In [6]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

In [7]:
# load dataset using pandas
titanic_train_df = pd.read_csv('./titanic/train.csv')
titanic_test_df = pd.read_csv('./titanic/test.csv')

In [8]:
titanic_Y_col = titanic_train_df.columns[1]
titanic_X_col = titanic_train_df.columns[2:]
titanic_X_col = titanic_X_col.drop(['Name','Ticket'])

In [9]:
titanic_X, titanic_Y = titanic_train_df[titanic_X_col].copy(), titanic_train_df[titanic_Y_col].copy()

In [10]:
numeric_cols = titanic_train_df[titanic_X_col].select_dtypes(include=np.number).columns.tolist()
categorical_cols = titanic_train_df[titanic_X_col].select_dtypes(exclude=np.number).columns.tolist()


In [11]:
# Impute and scale numeric columns
imputer = SimpleImputer().fit(titanic_train_df[numeric_cols])
titanic_X[numeric_cols] = imputer.transform(titanic_X[numeric_cols])


scaler = MinMaxScaler().fit(titanic_X[numeric_cols])
titanic_X[numeric_cols] = scaler.transform(titanic_X[numeric_cols])

In [12]:
# One-hot encode categorical columns
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore').fit(titanic_X[categorical_cols])
encoded_cols = list(encoder.get_feature_names_out(categorical_cols))
titanic_X[encoded_cols] = encoder.transform(titanic_X[categorical_cols])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
<ipython-input-12-e4e5141b2300>:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  titanic_X[encoded_cols] = encoder.transform(titanic_X[categorical_cols])
<ipython-input-12-e4e5141b2300>:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  titanic_X[encoded_cols] = enc

In [13]:
titanic_X = titanic_X[numeric_cols + encoded_cols]

In [14]:
titanic_X_Train, titanic_X_Test, titanic_Y_Train, titanic_Y_Test = train_test_split(titanic_X, titanic_Y, test_size = 0.30,random_state = 42)

In [15]:
!pip install -U pymoo

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 22.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 249.1/249.1 kB 17.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.9/75.9 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 13.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 20.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for grapheme: filename=grapheme-0.6.0-py3-none-any.whl size=210079 sha256=edb34c09e396239dd335d45bddcade09774da7d0adbce06a565e8eae8c199cef
  Stored in directory: /root/.cache/pip/wheels/01/e1/49/37e6bde9886439057450c494a79b0bef8bbe897a54aebfc757
Successfully built grapheme


In [16]:
from pymoo.algorithms.moo.nsga3 import NSGA3
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.factory import get_problem, get_reference_directions, get_sampling, get_crossover, get_mutation, get_termination
from pymoo.operators.selection.rnd import RandomSelection
from pymoo.operators.crossover.sbx import SBX
from pymoo.operators.mutation.pm import PolynomialMutation
from pymoo.termination.default import DefaultMultiObjectiveTermination
from pymoo.core.problem import Problem
from pymoo.optimize import minimize
from pymoo.operators.sampling.lhs import LHS

In [17]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
%matplotlib inline
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [18]:
def test_params(**params):
    model = RandomForestClassifier(random_state=42, n_jobs=-1, **params).fit(titanic_X_Train, titanic_Y_Train)
    train_accuracy_score = accuracy_score(titanic_Y_Train, model.predict(titanic_X_Train))
    val_accuracy_score = accuracy_score(titanic_Y_Test, model.predict(titanic_X_Test))
    return train_accuracy_score, val_accuracy_score

In [19]:
# define the hyperparameter optimization problem
class HyperparameterOptimizationProblem(Problem):

    def __init__(self,level):
        # define the lower and upper bounds of the hyperparameters
        # n_estimators: number of trees in the forest (integer)
        # max_depth: maximum depth of each tree (integer)
        # max_features: maximum number of features (integer)
        # min_samples_leaf: minimum number of samples required to be at a leaf node (integer)
        xl = np.array([1, 2, 2, 1, 0])
        xu = np.array([600, 12, 40, 9, 0.5])
        self.level=level

        # initialize the problem with 4 variables and 2 objectives
        super().__init__(n_var = 5, n_obj = 2, xl = xl, xu = xu)

    def _evaluate(self, x, out, *args, **kwargs):
        # evaluate each solution (each row of x)
        f = np.zeros((x.shape[0], self.n_obj))
        for i in range(x.shape[0]):
          if self.level==0:
            # get the hyperparameters
            n_estimators = int(x[i, 0])*3
            max_depth = int(x[i, 1])
            min_samples_split = int(x[i, 2])*2
            min_samples_leaf = int(x[i, 3])
            min_weight_fraction_leaf = int(x[i, 4])
          else:
            # get the hyperparameters
            n_estimators = int(x[i, 0])
            max_depth = int(x[i, 1])
            min_samples_split = int(x[i, 2])
            min_samples_leaf = int(x[i, 3])
            min_weight_fraction_leaf = int(x[i, 4])


            # build and train the random forest model
            model = RandomForestClassifier(n_estimators=n_estimators,
                                           max_depth=max_depth,
                                           min_samples_split=min_samples_split,
                                           min_samples_leaf = min_samples_leaf,
                                           min_weight_fraction_leaf = min_weight_fraction_leaf,
                                           max_features="sqrt",
                                           random_state=42,
                                           n_jobs = -1)
            model.fit(titanic_X_Train, titanic_Y_Train)

            # predict on the test set
            y_pred = model.predict(titanic_X_Test)

            # calculate the accuracy, f1 and ROC/AUC score as the objectives
            f[i, 0] = -accuracy_score(titanic_Y_Test, y_pred) # negate because we want to maximize
            f[i, 1] = -f1_score(titanic_Y_Test, y_pred) # negate because we want to maximize
            # f[i, 2] = -roc_auc_score(titanic_Y_Test, y_pred) # negate because we want to maximize


        # assign the objectives to the output dictionary
        out["F"] = f

In [20]:
%%time
# create an instance of the problem
problem = HyperparameterOptimizationProblem(level=0)
problem1 = HyperparameterOptimizationProblem(level=1)

# create an instance of NSGA-III algorithm
algorithm = NSGA2(
    pop_size= 100,
    #ref_dirs=get_reference_directions("das-dennis", 3, n_partitions=12),
    # sampling=get_sampling("int_random"),
    sampling=LHS(),
    selection = RandomSelection(),
    # crossover=get_crossover("int_sbx", prob=0.9, eta=15),
    crossover = SBX(prob=0.9, prob_var=0.8),
    mutation=PolynomialMutation(prob=0.8),
    eliminate_duplicates=True)

algorithm1 = NSGA2(
    pop_size= 50,
    #ref_dirs=get_reference_directions("das-dennis", 3, n_partitions=12),
    # sampling=get_sampling("int_random"),
    sampling=LHS(),
    selection = RandomSelection(),
    # crossover=get_crossover("int_sbx", prob=0.9, eta=15),
    crossover = SBX(prob=0.6, prob_var=0.5),
    mutation=PolynomialMutation(prob=0.5),
    eliminate_duplicates=True)

# create an instance of termination criterion
# termination = get_termination("n_gen", 50)

# early stop
termination = DefaultMultiObjectiveTermination(
    xtol=1e-8,           # movement in the design space xtol
    cvtol=1e-6,          # the convergence in the constraint cv_tol
    ftol=0.0025,         # objective space f_tol.
    period=30,
    n_max_gen=50,        # maximum number of generations n_max_gen
    n_max_evals=100000   # function evaluations n_max_evals
)

# perform the optimization
res = minimize(problem,
               algorithm,
               termination,
               seed=42,
               save_history=True,
               verbose=True)
res1 = minimize(problem1,
               algorithm1,
               termination,
               seed=42,
               seed_population=res.pop,
               save_history=True,
               verbose=True)

# print the results
print(f"Best solution found: \nX = {res1.X.astype(int)} \nF = {-res1.F}") # negate F because we maximized


n_gen  |  n_eval  | n_nds  |      eps      |   indicator  
     1 |      100 |    100 |             - |             -
     2 |      200 |    100 |  0.000000E+00 |             f
     3 |      300 |    100 |  0.000000E+00 |             f
     4 |      400 |    100 |  0.000000E+00 |             f
     5 |      500 |    100 |  0.000000E+00 |             f
     6 |      600 |    100 |  0.000000E+00 |             f
     7 |      700 |    100 |  0.000000E+00 |             f
     8 |      800 |    100 |  0.000000E+00 |             f
     9 |      900 |    100 |  0.000000E+00 |             f
    10 |     1000 |    100 |  0.000000E+00 |             f
    11 |     1100 |    100 |  0.000000E+00 |             f
    12 |     1200 |    100 |  0.000000E+00 |             f
    13 |     1300 |    100 |  0.000000E+00 |             f
    14 |     1400 |    100 |  0.000000E+00 |             f
    15 |     1500 |    100 |  0.000000E+00 |             f
    16 |     1600 |    100 |  0.000000E+00 |            

In [22]:
# print the results
print(f"Best solution found: \nX = {res1.X.astype(int)} \nF = {-res1.F}")

Best solution found: 
X = [[15  4 34  6  0]
 [15  4 35  6  0]
 [15  4 35  5  0]
 [15  4 39  6  0]
 [15  4 36  5  0]
 [15  4 33  5  0]
 [15  4 34  6  0]
 [15  4 35  5  0]
 [15  4 35  5  0]
 [15  4 35  6  0]
 [15  4 33  5  0]
 [15  4 35  5  0]
 [15  4 35  5  0]
 [15  4 34  5  0]
 [15  4 38  5  0]
 [15  4 35  5  0]
 [15  4 33  5  0]
 [15  4 35  6  0]
 [15  4 34  6  0]
 [15  4 35  5  0]
 [15  4 34  5  0]
 [15  4 35  5  0]
 [15  4 35  5  0]
 [15  4 35  5  0]
 [15  4 37  6  0]
 [15  4 35  6  0]
 [15  4 34  6  0]
 [15  4 35  5  0]
 [15  4 35  5  0]
 [15  4 34  6  0]
 [15  4 33  5  0]
 [15  4 36  5  0]
 [15  4 35  5  0]
 [15  4 36  6  0]
 [15  4 33  5  0]
 [15  4 35  5  0]
 [15  4 35  5  0]
 [15  4 35  6  0]
 [15  4 36  5  0]
 [15  4 34  5  0]
 [15  4 33  5  0]
 [15  4 33  5  0]
 [15  4 35  5  0]
 [15  4 36  5  0]
 [15  4 34  6  0]
 [15  4 35  5  0]
 [15  4 35  5  0]
 [15  4 35  5  0]
 [15  4 37  6  0]
 [15  4 35  5  0]] 
F = [[0.82462687 0.76616915]
 [0.82462687 0.76616915]
 [0.82462687 0.766